Strenght scripts

diff --git a/src/main/scripts/install b/src/main/scripts/install
--- a/src/main/scripts/install
+++ b/src/main/scripts/install
@@ -24,130 +24,137 @@
 
 # Installs all scripts of the utility.
 #
-# Version: 2014-02-14 1-RC
+# Version: 2022-05-20 1-RC
 # Author: Andres Gomez Casanova (AngocA)
 # Made in COLOMBIA.
 
+# Security options.
+set -euf
+
 # Global variables
-export continue=true
-export adminInstall=true
-export temporalTable=false
-export v9_7=false
+export CONTINUE=true
+export ADMIN_INSTALL=false
+export TEMPORAL_TABLE=false
+export V9_7=false
 
 # Installs a given script.
 # It uses the continue global variable to stop the execution if an error occurs.
+#
+# 1) Filename of the script to execute.
 installScript() {
- script=${1}
- echo $script
- db2 -tsf ${script}
- if [ ${?} -ne 0 ] ; then
-  export continue=false
+ SCRIPT=${1}
+ echo "${SCRIPT}"
+ set +e
+ db2 -tsf "${SCRIPT}"
+ RET=${?}
+ set -e
+ if [ ${RET} -ne 0 ] ; then
+  export CONTINUE=1
  fi
- unset script
+ unset SCRIPT
 }
 
 # Function that install the utility for version 10.1.
 # DB2 v10.1.
 v10_1() {
- local  __retInstall=$1
+ local __retInstall=${1}
  echo "Installing utility for v10.1"
- if [ ${adminInstall} = true ] ; then
-  [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/00-AdminObjects.sql
+ cd "${LOG4DB2_SRC_MAIN_CODE_PATH}"
+ if [ "${ADMIN_INSTALL}" = true ] ; then
+  [ "${CONTINUE}" = true ] && installScript 00-AdminObjects.sql
  fi
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/01-Tables.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/02-UtilityHeader.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/03-UtilityBody.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/04-Appenders.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/05-LOG.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/06-GET_LOGGER.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/07-Trigger.sql
+ [ "${CONTINUE}" = true ] && installScript 01-Tables.sql
+ [ "${CONTINUE}" = true ] && installScript 02-UtilityHeader.sql
+ [ "${CONTINUE}" = true ] && installScript 03-UtilityBody.sql
+ [ "${CONTINUE}" = true ] && installScript 04-Appenders.sql
+ [ "${CONTINUE}" = true ] && installScript 05-LOG.sql
+ [ "${CONTINUE}" = true ] && installScript 06-GET_LOGGER.sql
+ [ "${CONTINUE}" = true ] && installScript 07-Trigger.sql
 
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/08-AdminHeader.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/09-AdminBody.sql
+ [ "${CONTINUE}" = true ] && installScript 08-AdminHeader.sql
+ [ "${CONTINUE}" = true ] && installScript 09-AdminBody.sql
 
- cd ${LOG4DB2_SRC_MAIN_CODE_PATH}
- cd ..
- cd xml
- [ ${continue} = true ] && installScript 10-AppendersXML.sql
- cd ..
- cd scripts 2> /dev/null
+ cd ../xml
+ [ "${CONTINUE}" = true ] && installScript 10-AppendersXML.sql
+ cd ../sql-pl
 
  # Temporal capabilities for tables.
- if [ ${temporalTable} = true -a ${continue} = true ] ; then
+ if [ "${TEMPORAL_TABLE}" = true ] && [ "${CONTINUE}" = true ] ; then
   echo "Create table for Time Travel"
-  installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/11-TablesTimeTravel.sql
+  installScript 11-TablesTimeTravel.sql
  fi
 
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/12-Version.sql
+ [ "${CONTINUE}" = true ] && installScript 12-Version.sql
 
- local  myRetInstall=${continue}
- eval $__retInstall="'${myRetInstall}'"
+ local myRetInstall=${CONTINUE}
+ eval "$__retInstall"="'${myRetInstall}'"
 }
 
 # Function that install the utility for version 9.7.
 # DB2 v9.7
 v9_7() {
- local  __retInstall=$1
+ local __retInstall=${1}
  echo "Installing utility for DB2 v9.7"
- if [ ${adminInstall} = true ] ; then
-  [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/00-AdminObjects.sql
+ cd "${LOG4DB2_SRC_MAIN_CODE_PATH}"
+ if [ "${ADMIN_INSTALL}" = true ] ; then
+  [ "${CONTINUE}" = true ] && installScript 00-AdminObjects.sql
  fi
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/01-Tables_v9_7.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/02-UtilityHeader.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/03-UtilityBody.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/04-Appenders.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/05-LOG.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/06-GET_LOGGER_v9_7.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/07-Trigger.sql
+ [ "${CONTINUE}" = true ] && installScript 01-Tables_v9_7.sql
+ [ "${CONTINUE}" = true ] && installScript 02-UtilityHeader.sql
+ [ "${CONTINUE}" = true ] && installScript 03-UtilityBody.sql
+ [ "${CONTINUE}" = true ] && installScript 04-Appenders.sql
+ [ "${CONTINUE}" = true ] && installScript 05-LOG.sql
+ [ "${CONTINUE}" = true ] && installScript 06-GET_LOGGER_v9_7.sql
+ [ "${CONTINUE}" = true ] && installScript 07-Trigger.sql
 
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/08-AdminHeader.sql
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/09-AdminBody.sql
+ [ "${CONTINUE}" = true ] && installScript 08-AdminHeader.sql
+ [ "${CONTINUE}" = true ] && installScript 09-AdminBody.sql
 
- cd ${LOG4DB2_SRC_MAIN_CODE_PATH}
- cd ..
- cd xml
- [ ${continue} = true ] && installScript 10-AppendersXML.sql
- cd ..
- cd scripts 2> /dev/null
+ cd ../xml
+ [ "${CONTINUE}" = true ] && installScript 10-AppendersXML.sql
+ cd ../sql-pl
 
- [ ${continue} = true ] && installScript ${LOG4DB2_SRC_MAIN_CODE_PATH}/12-Version.sql
+ [ "${CONTINUE}" = true ] && installScript 12-Version.sql
 
- local  myRetInstall=${continue}
- eval $__retInstall="'${myRetInstall}'"
+ local myRetInstall=${CONTINUE}
+ eval "$__retInstall"="'${myRetInstall}'"
 }
 
 # This function checks all parameters and assign them to global variables.
 checkParam() {
- param1=${1}
- param2=${2}
- param3=${3}
- if [ "${param1}" = "-A" -o "${param2}" = "-A" -o "${param3}" = "-A" ] ; then
-  export adminInstall=false
+ local PARAM1=${1}
+ local PARAM2=${2}
+ local PARAM3=${3}
+ if [ "${PARAM1}" = "-A" ] || [ "${PARAM2}" = "-A" ] || [ "${PARAM3}" = "-A" ] ; then
+  export ADMIN_INSTALL=true
  fi
- if [ "${param1}" = "-t" -o "${param2}" = "-t" -o "${param3}" = "-t" ] ; then
-  export temporalTable=true
+ if [ "${PARAM1}" = "-t" ] || [ "${PARAM2}" = "-t" ] || [ "${PARAM3}" = "-t" ] ; then
+  export TEMPORAL_TABLE=true
  fi
- if [ "${param1}" = "-v9_7" -o "${param2}" = "-v9_7" -o "${param3}" = "-v9_7" ] ; then
-  export v9_7=true
+ if [ "${PARAM1}" = "-v9_7" ] || [ "${PARAM2}" = "-v9_7" ] || [ "${PARAM3}" = "-v9_7" ] ; then
+  export V9_7=true
  fi
 }
 
 # Main function that starts the installation.
 init() {
- local  __retInit=$1
+ local __retInit=${1}
  # Initialize the environment.
  if [ -x init ] ; then
   . ./init
+ else
+  echo "Error: File 'init' missing or without execute permissions."
+  exit 1
  fi
 
  echo "log4db2 is licensed under the terms of the Simplified-BSD license"
 
  # Check the given parameters.
- checkParam ${2} ${3} ${4}
+ checkParam "${2}" "${3}" "${4}"
 
  # Checks in which DB2 version the utility will be installed.
  # DB2 v10.1 is the default version.
- if [ "${v9_7}" = "true" ] ; then
+ if [ "${V9_7}" = true ] ; then
   v9_7 retInstall
  else
   v10_1 retInstall
@@ -158,42 +165,49 @@ init() {
  echo "To report an issue or provide feedback, please visit:"
  echo "https://github.com/angoca/log4db2/issues"
  echo
- if [ ${retInstall} = "true" ] ; then
+ if [ "${retInstall}" ] ; then
   echo "log4db2 was successfully installed"
   db2 -x "values 'Database: ' || current server"
   db2 -x "values 'Version: ' || logger.version"
   db2 -x "select 'Schema: ' || base_moduleschema from syscat.modules where moduleschema = 'SYSPUBLIC' and modulename = 'LOGGER'"
-  retValue=0
+  RET_VALUE=0
  else
   echo "Check the ERROR(s) and reinstall the utility"
   echo "For more information visit check the FAQs:"
   echo "https://github.com/angoca/log4db2/wiki/FAQs"
   echo "You can also check the install guide:"
   echo "https://github.com/angoca/log4db2/wiki/Install"
-  retValue=1
+  RET_VALUE=1
  fi
- unset continue
+ unset CONTINUE
 
  # Clean environment.
+ cd "${LOG4DB2_SRC_MAIN_SCRIPT_PATH}"
  if [ -x uninit ] ; then
   . ./uninit
+ else
+  echo "Error: File 'uninit' missing or without execute permissions."
+  exit 2
  fi
 
- local  myRetInit=${retValue}
- eval $__retInit="'${myRetInit}'"
+ local  myRetInit=${RET_VALUE}
+ eval "$__retInit"="'${myRetInit}'"
 }
 
 # Checks if there is already a connection established
+set +e
 db2 connect > /dev/null
-if [ ${?} -eq 0 ] ; then
- init ret ${1} ${2} ${3}
+RET=${?}
+set -e
+if [ ${RET} -eq 0 ] ; then
+ init ret "${1:-}" "${2:-}" "${3:-}"
 else
  echo "Please connect to a database before the execution of the installation."
  echo "Remember that to call the script the command is '. ./install'"
  ret=2
 fi
 
-unset continue
+unset CONTINUE
 
 return ${ret}
 
